#!/bin/bash

# Get the current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Activate the virtual environment
# Check if the environment is named .venv
if [[ -d $DIR/.venv/ ]]; then
    source "$DIR/.venv/bin/activate"
elif [[ -d $DIR/venv/ ]]; then
    source $DIR/venv/bin/activate
else
    echo "No virtual environment found. Please run setup first."
    exit 1
fi

# Grab any arguments
args=$@

# Run Bridge
python "$DIR/bridge.py" $args
