version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
      - /code/node_modules/
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/code
      - /code/.venv/