#!/bin/bash

# Set up the environment
if [ ! -d venv ]; then
    virtualenv venv
fi

# Activate the environment
source venv/bin/activate

# Install the requirements
pip install -r requirements.txt

# Run the initial setup
python bridge.py --initial_setup